name: amiga_gracia
description: Amiga Gracia Travel Services — Book ferry, airline, and tour packages.
version: 1.0.111+122

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  http: any
  url_launcher: any
  image_picker: any
  shared_preferences: any
  open_filex: any
  package_info_plus: any
  path_provider: any
  intl: any
  flutter_app_badger: any
  video_player: any
  flutter_local_notifications: any
  flutter_svg: any
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/icon/amiga_logo_white_outline.png
